### ISSUE TITLE
display form errors

### ISSUE THREAD

**Issue by tizianozonta** [loadsys/twitter-bootstrap-helper#1]
Hi,
I've some problems to display form errors, so i trying to debug the code.
I think there is an error at line 201:

if (strpos (".", $ options ['field'])! == false)

instead of

if (strpos ($ options ['field'], ".")! == false)

also at line 224

$options ['type'] = 'error';

instead of

$ options ['state'] = 'error';

correct?

PS: very useful helper! thanks

**Comment by joeytrapp** [comment]
Thanks you! Is this for Bootstrap Helper 2? The 2.0 branch input() method is still being refactored.

**Comment by tizianozonta** [comment]
yes, for Bootstrap Helper 2... so I'll expect the new version of code! :)

**Comment by joeytrapp** [comment]
I've committed some code and tested the form errors. They are working now, and will properly set the state of the control div to error and adds the error message to the help_block.
