### ISSUE TITLE
Input Select Option

### ISSUE THREAD

**Issue by kevinoconnor7** [loadsys/twitter-bootstrap-helper#10]
Small bug with using the input method, if you use a dropdown and specified the selected option, it is not carried through.

You're missing

``` php
if (isset($options["selected"])) {
    $opt["selected"] = $options["selected"];
}
```

in `_combine_input()`

**Comment by joeytrapp** [comment]
Thanks. I'm not going to add this, but instead unset the options that are not meant to be passed to the input() method and pass all of $options. I've been needing to pass in a 'placeholder' and some 'data-attr' attributes. Keep a look out for this update.

**Comment by joeytrapp** [comment]
This should now be solved.
