### ISSUE TITLE
wrong class for btn-disabled

### ISSUE THREAD

**Issue by tincho** [loadsys/twitter-bootstrap-helper#19]
file: View/Helper/BootstrapFormHelper.php line #444

http://twitter.github.com/bootstrap/base-css.html#buttons says:

> Heads up! We use .disabled as a utility class here, similar to the common .active class, so no prefix is required.

**Comment by joeytrapp** [comment]
Fortunately, I'm in the middle of some fixes.

https://github.com/loadsys/twitter-bootstrap-helper/pull/21
