### ISSUE TITLE
option "class" has no effect when using $this->TwitterBootstrap->input

### ISSUE THREAD

**Issue by tincho** [loadsys/twitter-bootstrap-helper#5]
this hasnt the expected result:
$this->TwitterBootstrap->input('name', array('class' => 'myfieldclass') );

which would be something like <input name="data[model][name]" class="myfieldclass" />

just added the line

if(!empty($options['class'])) $opt['class'] = $options['class']; 

on line 268 (method _combine_input)

not sure of how to submit a pull request and no per-line comments allowed so excuse me for skipping the "formal protocol"

**Comment by joeytrapp** [comment]
I've just added support for the class option, and a test assertion for it. This is now in 2.0 and master.
