### ISSUE TITLE
Contents

### ISSUE THREAD

**Issue by trante** [loadsys/twitter-bootstrap-helper#6]
Thank you for great helper, that was what i was looking for these days..

Does this class contains all Bootstrap components/features, or do you have a plan to integrate them later?

Thanks.

**Comment by joeytrapp** [comment]
I've been thinking of a possibly component, maybe at least something to wrap the SessionComponent::setFlash method, and it would auto load the helper if it wasn't in the helpers array. We are still discussing that internally.

**Comment by joeytrapp** [comment]
Sorry, I think I misread you post at first. The helper only has methods for parts of the bootstrap helper, and we are internally discussing what other parts we might include. If you have suggestions, we'd love to hear them.

**Comment by joeytrapp** [comment]
Closing this issue for being open for so long. If you have suggestions for more functionality to include, review the new structure in the 2.1 branch and open new issues for the new feature requests.
